tag: imagenet
eval_name: imagenet_classification
nodes: 4
tasks_per_node: 8
cpus_per_task: 10
num_probe_blocks: 1
resume_checkpoint: false
data:
  dataset_name: 'ImageNet'
  num_classes: 1000
  # root_path: None
  # image_folder: None
optimization:
  num_epochs: 10
  batch_size: 32
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.00001
  warmup: 0.1
  use_bfloat16: false
  weight_decay: 0.04
pretrain:
  model_name: vit_h
  tubelet_size: 2
  pos_embed_type: 3d
  use_xformers: false
  use_sdpa: false
  patch_size: 16
  folder: "/checkpoint/soniajoseph/v1_vit_huge_conv/"
  write_tag: jepa
  


# args_eval = {
#     'pretrain': {
#         'checkpoint_key': 'target_encoder',
#         'model_name': 'vit_huge',
#         'patch_size': 16,
#         'folder':  "/checkpoint/soniajoseph/v1_vit_huge_conv/",
#         'ckp_fname': 'model_checkpoint.pth',
#         'tag': 'my_model_tag',
#         'use_sdpa': True,
#         'use_silu': False,
#         'wide_silu': True,
#         'uniform_power': False,
#         'is_causal': False
#     },
#     'data': {
#         'dataset_name': 'ImageNet',
#         'num_classes': 1000,
#         'root_path': None,
#         'image_folder': None,
#     },
#     'optimization': {
#         'batch_size': 32,
#         'num_epochs': 10,
#         'wd': 1e-6,
#         'start_lr': 1e-4,
#         'lr': 1e-3,
#         'final_lr': 1e-5,
#         'warmup': 0.1,
#         'use_bfloat16': False
#     },
#     'num_probe_blocks': 1,
#     'resume_checkpoint': False,
#     'tag': 'my_model_tag'
# }